AWSTemplateFormatVersion: 2010-09-09
Description: 
 This CloudFormation template
 was written for running Kittens 
 Carousel Static Website on EC2.
 This Website is deployed on Amazon Linux2
 (ami...) Ec2 instance with custom security 
 group which allows port 80 and 22 for SSH access.
 This static website is downloaded from my 
 GitHub account to be deployed on Apache server.


Parameters:
Metadata:
Mappings:
Conditions:
Transform:

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables HTTP port 80 and Port 22 for SSH access. 
      SecurityGroupIngress:
        - IPprotocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IPprotocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: fist_key_pair
      DisableApiTermination: 
      ImageId: ami-02396cdd13e9a1257 
      InstanceType: t2.micro 
      SecurityGroupIds:
        - ref: WebServerSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: !sub Web server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/serdarcw/project-repository/master/Project-101-kittens-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            wget ${FOLDER}/cat3.png
            systemctl start httpd
            systemctl enable httpd  








Outputs:
